// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbfsvbgrpexuzmvzvlpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiZnN2YmdycGV4dXptdnp2bHBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNTMzMTcsImV4cCI6MjA3MTgyOTMxN30.jQb2Yfq_IaOuFo1oaDISsl6-RxVtKKNct-eTuggWHRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});